import turtle
f = turtle.Pen()
f.shape('circle')
f.width(5)
f.color('green')
f.begin_fill()
f.goto(0,100)
f.right(90)
f.forward(400)
f.right(180)
f.begin_fill()
for i in range(2):
    f.circle(100,90)
    f.left(90)
f.end_fill()
f.goto(0,-200)
f.color('light green')
f.begin_fill()
for ii in range(2):
    f.circle(-100,90)
    f.right(90)
f.end_fill()
f.penup()
f.goto(0,100)
f.pendown()
f.color('yellow','pink')
f.begin_fill() 
for i in range(5):
    for ii in range(6):
        f.forward(100)
        f.right(60)
    f.right(72)
f.end_fill()
turtle.done()
